version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - test-network

  test:
    build: .
    container_name: test
    working_dir: /tests
    depends_on:
      - app
    networks:
      - test-network
    command: sh -c "cd tests && npm install && npm test"

networks:
  test-network: