version: "3.8"

services:
  app:
    build: .
    container_name: app
    ports:
      - "3000:3000"
    networks:
      - test-network

  test:
  build: .
  working_dir: /app
  command: sh -c "npm install --prefix tests && npm test --prefix tests"

networks:
  test-network: